# file: apache/tasks/main.yml
# descriptrion: file contains tasks for apache

---

- name: 'Ensure httpd package is present'
  yum:
    name: httpd
    state: present

- name: 'Upload main.html'
  template:
    src: 'main.html.j2'
    dest: '/var/www/html/index.html'
  become: yes

- name: 'Delete default Apache page'
  file:
    state: absent
    path: '/etc/httpd/conf.d/welcome.conf'
  become: yes

- name: 'Ensure httpd is started'
  service:
    name: httpd
    state: started
